name: VirusTotal Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan files
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./Get-ShodanAPIInfo/Get-ShodanAPIInfo.psm1
            ./Get-ShodanClientHTTPHeaders/Get-ShodanClientHTTPHeaders.psm1
            ./Get-ShodanClientIP/Get-ShodanClientIP.psm1
            ./Get-ShodanDNSDomain/Get-ShodanDNSdomain.psm1
            ./Get-ShodanDNSResolve/Get-ShodanDNSResolve.psm1
            ./Get-ShodanDNSReverse/Get-ShodanDNSReverse.psm1
            ./Get-ShodanExploitCount/Get-ShodanExploitCount.psm1
            ./Get-ShodanExploitSearch/Get-ShodanExploitSearch.psm1
            ./Get-ShodanHoneyScore/Get-ShodanHoneyScore.psm1
            ./Get-ShodanHostCount/Get-ShodanHostCount.psm1
            ./Get-ShodanHostIP/Get-ShodanHostIP.psm1
            ./Get-ShodanHostSearch/Get-ShodanHostSearch.psm1
            ./Get-ShodanHostSearchFacets/Get-ShodanHostSearchFacets.psm1
            ./Get-ShodanHostSearchFilters/Get-ShodanHostSearchFilters.psm1
            ./Get-ShodanPorts/Get-ShodanPorts.psm1
            ./Get-ShodanProfile/Get-ShodanProfile.psm1
            ./Get-ShodanScanID/Get-ShodanScanID.psm1
            ./Get-ShodanScanProtocols/Get-ShodanScanProtocols.psm1
            ./Set-ShodanScanIP/Set-ShodanScanIP.psm1








